
const CATEGORIES = [
    '2D',
    '3D',
    'AR / VR',
    'Advertising',
    'Animation',
    'Application design',
    'Architecture',
    'Artistic direction',
    'Branding',
    'Calligraphy',
    'Ceramics',
    'Character design',
    'Cinematography',
    'Collage',
    'Comic',
    'Conceptual art',
    'Copywriting',
    'Costume Design',
    'Creative direction',
    'Cryptoart',
    'Design of products',
    'Designs of objects or accessories',
    'Designs with paper',
    'Digital art',
    'Digital paint',
    'Display',
    'Drafting',
    'Editorial design',
    'Engineering',
    'Fashion design',
    'Fine arts',
    'Font design',
    'GIF',
    'Game design',
    'Gastronomy',
    'Graffiti',
    'Graphic design',
    'Handicrafts',
    'Icon design',
    'Illustration',
    'Industrial design',
    'Infographics',
    'Interactive layout',
    'Interior design',
    'Jewelry design',
    'Journalism',
    'Lettering',
    'Logo design',
    'Makers',
    'Mockup',
    'Mapping',
    'Modeling',
    'Movie theater',
    'Music',
    'Packaging',
    'Painting',
    'Performing arts',
    'Photography',
    'Photojournalism',
    'Pixelart',
    'Programming',
    'Retouching images',
    'Scenography',
    'Sculpture',
    'Sound design',
    'Street art',
    'Styling',
    'Textile design',
    'Typography',
    'UX / UI design',
    'Visual effects',
    'Web design',
    'Wood work',
    'Writing'
];

const SELECTABLE_CATEGORIES = [];

CATEGORIES.forEach(c => {
    SELECTABLE_CATEGORIES.push({
        tag: c.replaceAll(' ', '').replaceAll('/', '').toLowerCase(),
        text: c
    })
})

export {
    CATEGORIES, SELECTABLE_CATEGORIES
};
