/**
 * Created by ander on 29/09/18.
 */
export const SESSION = 'CREARY_SESSION',
    ACCESS_TOKEN = 'CREARY_ACCESS_TOKEN',
    ACCESS_TOKEN_EXPIRATION = 'CREARY_ACCESS_TOKEN_EXPIRATION',
    LANG = 'CREARY_LANGUAGE',
    OBFUSCATED_SESSION = 'CREARY_OBFUSCATED_SESSION';
